In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

question1)Write a program to find average of all the even numbers, and
odd number that are present in the list. And also your program
shold be return no. of evens and odd are present in this list List
for your reference
lst = [25,41,85,96,35,64,75,9,12,21,32,23,25,56]

In [126]:
lst = [25,41,85,96,35,64,75,9,12,21,32,23,25,56]

In [127]:
even=[]
odd=[]
for item in lst:
    if item%2==0:
        even.append(item)
    else:
        odd.append(item)


In [128]:
total_sum_even=sum(even)
total_even=len(even)
avg_even=total_sum_even/total_even
print('total even no. in the list are ',total_even)
print('average of even is',avg_even)

total even no. in the list are  5
average of even is 52.0


In [129]:
total_sum_odd=sum(odd)
total_odd=len(odd)
avg_odd=total_sum_odd/total_odd
print('total even no. in the list are ',total_odd)
print('average of odd is',avg_odd)

total even no. in the list are  9
average of odd is 37.666666666666664


question2)Write a program to find the target element from the list, with
linear search and Binary Search.


Linear search-Searches for an element by visiting all the elements sequentially until the element is found.

Binary search-Searches for an element by breaking the search space into half in a sorted array.


In [130]:
df=np.array(lst)
df

array([25, 41, 85, 96, 35, 64, 75,  9, 12, 21, 32, 23, 25, 56])

In [131]:
target_element=64

**Linear search**

In [132]:
n=-1
for i in df:
    n+=1
    if i==target_element:
        print("target element found at index ",n)

target element found at index  5


**Binary search**

In [133]:
df

array([25, 41, 85, 96, 35, 64, 75,  9, 12, 21, 32, 23, 25, 56])

In [134]:
df.sort()

In [135]:
df

array([ 9, 12, 21, 23, 25, 25, 32, 35, 41, 56, 64, 75, 85, 96])

In [136]:
def binary_search(df,target_element):
    low=0
    high=13
    while (low<=high):
        mid= (high +low)//2
        if(df[mid]==target_element):
            return mid
        elif(df[mid]<target_element):
            low=mid+1
        else:
             high=mid-1
    return -1
result=binary_search(df,target_element)
print('element found at index',result)

element found at index 10


Learn about list comprehension and write a program to
generate a list of square element from this given list and also
try to filter all the even numbers from the given list using list
comprehension.
lst = [25,41,85,96,35,64,75,9,12,21,32,23,25,56]

list comprehension-concise way to create python list

In [137]:
lst = [25,41,85,96,35,64,75,9,12,21,32,23,25,56]

In [138]:
square=[i**2 for i in lst]

In [139]:
square

[625, 1681, 7225, 9216, 1225, 4096, 5625, 81, 144, 441, 1024, 529, 625, 3136]

In [140]:
even=[i for i in lst if i%2==0]

In [141]:
even

[96, 64, 12, 32, 56]

**LIFE CYCLE OF MACHINE LEARNING**

Firstly problem which we want to solve is discovered,then related data whichhas to be trained is searched,then it is preprocessed for the purpose of being trained,then data analysis is done,then data is trained and tested based on the algorithm required and lastly data is deployed that means used in real world